post_install() {
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload || true
		# systemctl restart microsoft-identity-device-broker.service || true
	fi
}

post_upgrade() {
	post_install
}

pre_remove() {
	if [ -d /run/systemd/system ]; then
		systemctl stop microsoft-identity-device-broker.service || true
	fi
}

post_remove() {
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload || true
	fi
}
